name = "RayChaudhuriWilson"
defaultTargets = ["RayChaudhuriWilson"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false # no "assume a typo is a new variable"
relaxedAutoImplicit = false # no "assume a typo is a new variable"
linter.style.longLine = true # no lines longer than 100 chars
linter.oldObtain = true # no "stream of consciousness `obtain`"
linter.style.multiGoal = true # no multiple active goals

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "leanprover/lean4:v4.18.0-rc1"

[[lean_lib]]
name = "RayChaudhuriWilson"